TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O0 -g
ASFLAGS = -g 

# object files

OBJS=  $(STARTUP) $(USART) main.o
OBJS+= stm32f4xx_gpio.o stm32f4xx_rcc.o stm32f4xx_usart.o misc.o

# include common make file

include $(TEMPLATEROOT)/Makefile.common


